### PR TITLE
Reducing publish size

### LINKED ISSUE #450: circle-ci is publishing nearly 4gb for papiea. This is too much.
```
./papiea-engine/publish-images.py
...
8b4a789aa55c: Pushing  3.616GB
```

### PR DESCRIPTION
**Pull request by Emulebest**
resolves #450

### CODE REVIEW

**Comment by Emulebest** [comment]
> `.circleci/Dockerfile.publish` Do we need separate `Dockerfile`s? I'd really like to have the absolute minimum number of docker and docker-compose files, otherwise maintaining all of them becomes a challenge.

Yeah, I am totally planning to leave a single Dockerfile but my current plan is:
1) optimize size without breaking the components
2) refactor different envs (dev, prod) to use different stages of builds

**Comment by Emulebest** [comment]
For now the image size is 1.79 Gb, which seems to be a reasonable amount. We could shrink it even further but that would change OS dist to `alpine` which is going to limit us in the future. The distribution for the size looks as follows:
```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
414ea752d972        37 minutes ago      /bin/sh -c #(nop)  CMD ["/bin/sh" "-c" "/bin…   0B                  
<missing>           37 minutes ago      /bin/sh -c #(nop)  ENV PATH=/usr/local/sbin:…   0B                  
<missing>           37 minutes ago      /bin/sh -c curl -o- -L yarnpkg.com/install.s…   7.59MB              
<missing>           37 minutes ago      /bin/sh -c #(nop) WORKDIR /code/papiea-engine   0B                  
<missing>           37 minutes ago      /bin/sh -c #(nop) COPY dir:3aed4c6445e4fb4f3…   837MB               
<missing>           23 hours ago        /bin/sh -c #(nop)  CMD ["node"]                 0B                  
<missing>           23 hours ago        /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry…   0B                  
<missing>           23 hours ago        /bin/sh -c #(nop) COPY file:238737301d473041…   116B                
<missing>           23 hours ago        /bin/sh -c set -ex   && for key in     6A010…   7.73MB              
<missing>           23 hours ago        /bin/sh -c #(nop)  ENV YARN_VERSION=1.22.4      0B                  
<missing>           23 hours ago        /bin/sh -c ARCH= && dpkgArch="$(dpkg --print…   100MB               
<missing>           23 hours ago        /bin/sh -c #(nop)  ENV NODE_VERSION=14.7.0      0B                  
<missing>           23 hours ago        /bin/sh -c groupadd --gid 1000 node   && use…   333kB               
<missing>           40 hours ago        /bin/sh -c set -ex;  apt-get update;  DEBIAN…   561MB               
<missing>           40 hours ago        /bin/sh -c apt-get update && apt-get install…   142MB               
<missing>           40 hours ago        /bin/sh -c set -ex;  if ! command -v gpg > /…   7.81MB              
<missing>           40 hours ago        /bin/sh -c apt-get update && apt-get install…   23.2MB              
<missing>           2 days ago          /bin/sh -c #(nop)  CMD ["bash"]                 0B                  
<missing>           2 days ago          /bin/sh -c #(nop) ADD file:a28d8a949b7577768…   101MB
```

**Comment by shlomi-nx** [comment]
Can you provide some info on the large items in the list? I'd like to know what are the entries that takes more than a 100mb

**Comment by Emulebest** [comment]
> Can you provide some info on the large items in the list? I'd like to know what are the entries that takes more than a 100mb

`<missing>           37 minutes ago      /bin/sh -c #(nop) COPY dir:3aed4c6445e4fb4f3…   837MB` is our project files directory (papiea-engine)

`<missing>           23 hours ago        /bin/sh -c ARCH= && dpkgArch="$(dpkg --print…   100MB` is a utility to build .deb packages on arch (not sure why it is here, it's part of `node` image)

```
<missing>           40 hours ago        /bin/sh -c set -ex;  apt-get update;  DEBIAN…   561MB               
<missing>           40 hours ago        /bin/sh -c apt-get update && apt-get install…   142MB
```
are debian packages.

`<missing>           2 days ago          /bin/sh -c #(nop) ADD file:a28d8a949b7577768…   101MB` - I am unsure of what this file does, will try to investigate

**Comment by shlomi-nx** [comment]
Thanks for the details. Can we double check all the dependencies we use? Perhaps >800MB for the project directory is a bit large. We seem to keep dev packages in node_modules, use `npm prune --production` or others to  to remove these.

After cleaning up all node_modules and the clojure build. the raw size is really small:
```
(master) > du -h . -d 1 
1.3M	./papiea-engine
220K	./papiea-client
16K	./.circleci
9.4M	./.git
588K	./papiea-sdk
48K	./papiea-backend-utils
32K	./papiea-core
12M	.
```

After build it jumped to 1.2GB:

```
> yarn run build-all!                                                                                                                           /media/ebs-work/papiea-bmaasubuntu@ip-172-31-9-140
yarn run v1.22.4
$ yarn run clean-all && yarn run build-all
$ for p in core backend-utils client engine sdk/typescript; do yarn --cwd papiea-$p run clean || exit 1; done
...
[4/4] Building fresh packages...
$ yarn run tsc
$ /media/ebs-work/papiea-bmaas/papiea-sdk/typescript/node_modules/.bin/tsc
Done in 38.27s.
(master) > du -h . -d 1
370M	./papiea-engine
164M	./papiea-client
16K	./.circleci
9.4M	./.git
455M	./papiea-sdk
114M	./papiea-backend-utils
53M	./papiea-core
1.2G	.
```

However, after running `npm prune --production` on engine, it got reduced from 370MB to 71MB:
```
> npm prune --production
...

(master) > du -h . -d 1
1.1M	./build
108K	./__benchmarks__
60K	./papiea-lib-clj
352K	./__tests__
68M	./node_modules
516K	./src
71M	.
```

And after running `npm prune --production` on all folders we get 96MB instead of 1.2GB for the entire project:
```
> du -h . -d 1 
71M	./papiea-engine
1.4M	./papiea-client
16K	./.circleci
9.4M	./.git
6.0M	./papiea-sdk
8.5M	./papiea-backend-utils
64K	./papiea-core
96M	.
```

**Comment by Emulebest** [comment]
> Thanks for the details. Can we double check all the dependencies we use? Perhaps >800MB for the project directory is a bit large. We seem to keep dev packages in node_modules, use `npm prune --production` or others to to remove these.
> 
> After cleaning up all node_modules and the clojure build. the raw size is really small:
> 
> ```
> (master) > du -h . -d 1 
> 1.3M	./papiea-engine
> 220K	./papiea-client
> 16K	./.circleci
> 9.4M	./.git
> 588K	./papiea-sdk
> 48K	./papiea-backend-utils
> 32K	./papiea-core
> 12M	.
> ```
> 
> After build it jumped to 1.2GB:
> 
> ```
> > yarn run build-all!                                                                                                                           /media/ebs-work/papiea-bmaasubuntu@ip-172-31-9-140
> yarn run v1.22.4
> $ yarn run clean-all && yarn run build-all
> $ for p in core backend-utils client engine sdk/typescript; do yarn --cwd papiea-$p run clean || exit 1; done
> ...
> [4/4] Building fresh packages...
> $ yarn run tsc
> $ /media/ebs-work/papiea-bmaas/papiea-sdk/typescript/node_modules/.bin/tsc
> Done in 38.27s.
> (master) > du -h . -d 1
> 370M	./papiea-engine
> 164M	./papiea-client
> 16K	./.circleci
> 9.4M	./.git
> 455M	./papiea-sdk
> 114M	./papiea-backend-utils
> 53M	./papiea-core
> 1.2G	.
> ```
> 
> However, after running `npm prune --production` on engine, it got reduced from 370MB to 71MB:
> 
> ```
> > npm prune --production
> ...
> 
> (master) > du -h . -d 1
> 1.1M	./build
> 108K	./__benchmarks__
> 60K	./papiea-lib-clj
> 352K	./__tests__
> 68M	./node_modules
> 516K	./src
> 71M	.
> ```
> 
> And after running `npm prune --production` on all folders we get 96MB instead of 1.2GB for the entire project:
> 
> ```
> > du -h . -d 1 
> 71M	./papiea-engine
> 1.4M	./papiea-client
> 16K	./.circleci
> 9.4M	./.git
> 6.0M	./papiea-sdk
> 8.5M	./papiea-backend-utils
> 64K	./papiea-core
> 96M	.
> ```
I am pretty aware of `npm prune --production` but since we are using yarn it might yield incorrect results. 96 MB seems unrealistic IMO (but I may be wrong) because node is notorious for enormous build sizes. Actually I am cleaning devDependencies with a custom script because yarn lacks `npm prune` kind of command. 
If you could test that results done with `npm prune` work fine then we could go for that. Anyways, I would be able to also test that on Monday if you are busy.

**Pull request merged**
