### PR TITLE
Added default value for input & output in add_procedure_schema

### PR DESCRIPTION
**Pull request by nitesh-idnani1**
- Added default value for input & output in add_procedure_schema - api_docs

### CODE REVIEW

**Comment by Emulebest** [comment]
closing in favour of #614

**Review by shlomi-nx — COMMENTED** [review]
looks better, but this feels a little brittle..

**Comment by Emulebest** [comment]
> looks better, but this feels a little brittle..

@shlomi-nx This comment addresses #612 or #614?

**Comment by shlomi-nx** [comment]
@Emulebest #612, forgot this was closed in favor of the more complete #614, sorry for the confusion.

**Pull request closed without merging**
