### PR TITLE
Removed input tag from the constructor procedure schema in api docs

### LINKED ISSUE #603: new constructor schema contains `input` only on the swagger spec, visible in swagger ui
When trying to invoke with `input`, it gets denied by a schema error that seems wrong (complains that existing fields do not exist). When removing `input` it get accepted even though it does not match the schema.

### PR DESCRIPTION
**Pull request by nitesh-idnani1**
Closes #603
- Removed misleading input field tag from the constructor procedure schema function.
- Added WithEntityConstructor function to allow on_create handler in test data factory.

### CODE REVIEW

**Review by shlomiv — APPROVED** [review]
Looks good

**Review by Emulebest — CHANGES_REQUESTED** [review]
Please provide a test for this PR

**Comment by nitesh-idnani1** [comment]
@Emulebest 
Kindly review and merge this as well. Thanks

**Review by shlomi-nx — COMMENTED** [review]
looks good

**Pull request merged**
